routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

Route::get('/', [App\Http\Controllers\DashboardController::class, 'index'])->name('home');


Auth::routes();

Route::get('/logout', [App\Http\Controllers\HomeController::class, 'logout'])->name('logout');
Route::get('/changeLang/{lang}', [App\Http\Controllers\UserController::class, 'changeLang'])->name('changeLang');
// Role Prefix
Route::prefix('role')->group(function () {
    Route::get('/', [App\Http\Controllers\RoleController::class, 'index'])->name('role.index');
    Route::get('/create', [App\Http\Controllers\RoleController::class, 'create'])->name('role.create');
    Route::post('/', [App\Http\Controllers\RoleController::class, 'store'])->name('role.store');
    Route::get('/edit/{id}', [App\Http\Controllers\RoleController::class, 'edit'])->name('role.edit');
    Route::patch('/{id}', [App\Http\Controllers\RoleController::class, 'update'])->name('role.update');
    Route::get('role/delete/{id}', [App\Http\Controllers\RoleController::class, 'delete'])->name('role.delete');

    // Role Permission
    Route::get('/permission/{id}', [App\Http\Controllers\RoleController::class, 'rolePermission'])->name('role.permission');
    Route::post('/permission/store', [App\Http\Controllers\RoleController::class, 'storeRolePermission'])->name('role.permission.store');
});

// Department prefix
Route::prefix('department')->group(function () {
    Route::get('/', [App\Http\Controllers\DepartmentController::class, 'index'])->name('department.index');
    Route::get('/create', [App\Http\Controllers\DepartmentController::class, 'create'])->name('department.create');
    Route::post('/', [App\Http\Controllers\DepartmentController::class, 'store'])->name('department.store');
    Route::get('/edit/{id}', [App\Http\Controllers\DepartmentController::class, 'edit'])->name('department.edit');
    Route::patch('/{id}', [App\Http\Controllers\DepartmentController::class, 'update'])->name('department.update');
    Route::get('delete/{id}', [App\Http\Controllers\DepartmentController::class, 'destroy'])->name('department.delete');
    Route::get('/assign-department/{id}', [App\Http\Controllers\DepartmentController::class, 'assignDepartment'])->name('department.assign');
    Route::post('/assign-department/store', [App\Http\Controllers\DepartmentController::class, 'storeAssignDepartment'])->name('department.assign.store');
    Route::get('/assign-department/edit/{id}', [App\Http\Controllers\DepartmentController::class, 'editAssignDepartment'])->name('department.assign.edit');
    Route::patch('/assign-department/update/{id}', [App\Http\Controllers\DepartmentController::class, 'updateAssignDepartment'])->name('department.assign.update');
});
// User Prefix

Route::prefix('user')->group(function () {
    Route::get('/', [App\Http\Controllers\UserController::class, 'index'])->name('user.index');
    Route::get('/create', [App\Http\Controllers\UserController::class, 'create'])->name('user.create');
    Route::post('/', [App\Http\Controllers\UserController::class, 'store'])->name('user.store');
    Route::get('/edit/{id}', [App\Http\Controllers\UserController::class, 'edit'])->name('user.edit');
    Route::patch('/{id}', [App\Http\Controllers\UserController::class, 'update'])->name('user.update');
    Route::delete('/{id}', [App\Http\Controllers\UserController::class, 'destroy'])->name('user.delete');
});

// Request
Route::prefix('request')->group(function () {
    Route::get('/', [App\Http\Controllers\RequestController::class, 'index'])->name('request.index');
    Route::get('/create', [App\Http\Controllers\RequestController::class, 'create'])->name('request.create');
    Route::post('/', [App\Http\Controllers\RequestController::class, 'store'])->name('request.store');
    Route::get('/edit/{id}', [App\Http\Controllers\RequestController::class, 'edit'])->name('request.edit');
    Route::patch('/{id}', [App\Http\Controllers\RequestController::class, 'update'])->name('request.update');
    Route::get('/user-department/{id}', [App\Http\Controllers\RequestController::class, 'getUserDepartment'])->name('request.user.department');
    Route::get('/approve/{id}', [App\Http\Controllers\RequestController::class, 'approve'])->name('request.approve');
    Route::get('/approve/store/{id}/{status}', [App\Http\Controllers\RequestController::class, 'storeApprove'])->name('request.approve.store');
    Route::get('/request/request-history/{id}', [App\Http\Controllers\RequestController::class, 'requestHistory'])->name('request.request.history');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role_id',
        'language',
        'status',
        'photo'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    protected $appends = [
        'photo_url',
        'department_ids',
        'department_names',
    ];

    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    public function userDepartments()
    {
        return $this->belongsToMany(Department::class, 'user_departments', 'user_id', 'department_id')->orderBy('id', 'desc');
    }


    public function getPhotoUrlAttribute()
    {
        return $this->photo ? asset('uploads/users/' . $this->photo) : asset('uploads/users/avatar-place.png');
    }

    public function getRoleNameAttribute()
    {
        return $this->role->name ?? '';
    }
    public function getDepartmentIdsAttribute()
    {
        return $this->userDepartments->pluck('department_id')->toArray();
    }

    public function getDepartmentNamesAttribute()
    {
        return $this->userDepartments->pluck('name')->toArray();
    }


}

resources/views/Dashboard.blade.php
@extends('layouts.master')
@section('title')
{{__('setting.dashboard')}}
@endsection
@section('content')
  <!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card card-success card-outline">
          <div class="card-header card-profile">
            <h6 class="card-title text-success text-bold">
                 &nbsp;  &nbsp;<span>{{ __('user.my_profile')}}</span>
              </h6>
          </div>
          <div class="card-body">
            <div class="row">
              <div class="col-12 col-lg-12">
                <div style="margin-top:20px;" class="row">
                  <div class="container emp-profile">
                    <div class="row">
                      <div class="col-md-4">
                        <div class="profile-img">
                            <img width="50%" onclick="showImage(this)" src="{{Auth::user()->photo_url}}" class="img-responsive img-thumbnail" style="cursor: pointer;" alt=""/>
                         </div>
                       </div>
                        <div class="col-md-6">
                          <div class="profile-head">
                            <h5><b>  {{Auth::user()->name }}</b></h5><br>
                                <ul class="nav nav-tabs" id="custom-tabs-one-tab" role="tablist">
                                    <li class="nav-item">
                                        <a class="nav-link active" id="custom-tabs-one-home-tab" data-toggle="pill" href="#custom-tabs-one-home" role="tab" aria-controls="custom-tabs-one-home" aria-selected="true">{{__('user.about')}}</a>
                                    </li>
                                </ul>
                              </div>
                            </div>
                          </div>
                           <div class="tab-content" id="custom-tabs-one-tabContent">
                                    <!-- about -->
                              <div class="tab-pane fade show active" id="custom-tabs-one-home" role="tabpanel" aria-labelledby="custom-tabs-one-home-tab">
                                <div class="row">
                                  <div class="col-sm-0 col-lg-4">
                                  </div>
                                  <div class="col-sm-12 col-lg-8">
                                    <div class="row">
                                        <div class="col-3">
                                           <b class="text-success">{{__('user.name')}} :</b>
                                        </div>
                                        <div class="col-9">
                                              {{Auth::user()->name}}
                                        </div>
                                         </div><br>
                                      <div class="row">
                                        <div class="col-3"><b class="text-success">{{__('user.email')}} :</b> </div>
                                            <div class="col-9">{{maskText(Auth::user()->email)}} </div>
                                              </div><br>
                                        <div class="row">
                                                <div class="col-3"><b class="text-success">{{__('setting.department')}} :</b></div>
                                                <div class="col-9">
                                                  @foreach(Auth::user()->department_names as $department_name)
                                                    <span class="badge badge-info">{{$department_name}}</span>
                                                  @endforeach
                                                </div>
                                            </div><br>
                                      @if(isOwner())
                                      <div class="row">
                                          <div class="col-3"><b class="text-success">{{__('user.role')}} :</b></div>
                                          <div class="col-9"> {{Auth::user()->role_name}} </div>
                                      </div><br>
                                      @endif
                                      <div class="row">
                                        <div class="col-3"><b class="text-success">{{__('user.password')}} :</b></div>
                                         <div class="col-9">*******</div>
                                      </div>
                                      </div>
                                    </div>
                                    </div>
                  
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
           </section>
        @section('js')
      <script>
        function preview(e){

        var img_link = document.getElementById('prev');
             img_link.src = URL.createObjectURL(e.target.files[0]);
         
        }
      </script>
    @endsection
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection